### PR TITLE
Update IBusChewingLookupTable.c

### PR DESCRIPTION
**Pull request by hiunnhue**
This commit contains the following modifications:

1. Since ibus-chewing resizes the lookup table when enabled and
focus in, there should be no need to resize again when opening it.

2. If I'm not mistaken, the length of selkeys is equivalent to
the number of candidats per page. It should be okay to use the
value of "cand-per-page" directly.

3. The labels of lookup table are converted to uppercase, with a
dot after it, just like the default one.

### CODE REVIEW

**Comment by hiunnhue** [comment]
修改後的效果：

lookup_table

**Comment by definite** [comment]
It may be possible that length of selKeys  and cand-per-page are inconsistent when user specify their own selKeys.

**Comment by hiunnhue** [comment]
噢… ibus-chewing 原本是打算讓使用者自訂選字鍵的嗎？

但之前的 Pull Request #87 已經把選字鍵改成下拉式選單，不讓使用者自行輸入…

當初會這樣改，是因為一旦試圖輸入，ibus-setup-chewing 就會崩潰關閉

**Comment by hiunnhue** [comment]
我把原本的長度檢查改回去了，但因為選字鍵和每頁候選字的上限都是10，應該只要比較一次就好。

其他的部份沒有改變。

**Comment by definite** [comment]
Thanks for your contribution.

**Pull request merged**
